# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Software Developer"
  name: "Saket Upadhyay"
  username: "Saket1972" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/my-avatar.png"

INFO:
  - label: "Email"
    value: "saketofficial72@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "9453306699"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "november 16 2004"
    icon: "calendar-outline"
  - label: "Location"
    value: "Vellore , TamilNadu"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/"
  - icon: "logo-github"
    url: "https://github.com/ivansaul"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
